# Generated by Django 3.1.4 on 2020-12-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_id', models.CharField(max_length=50)),
                ('care', models.CharField(max_length=50)),
            ],
        ),
    ]
